include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Lint & Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:trion_ng-cli-karma_11.2.6
  stage: build
  script:
    - cd client/
    - npm install
    - npm run lint
    - npm run test
