include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Test:
  image: quay.io/ebi-ait/ingest-base-images:node_14.15.5-alpine
  stage: test
  before_script:
    - yarn install --frozen-lockfile --no-progress
    - apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
  script:
    - yarn lint
    - yarn test --watch false --browsers=ChromeHeadlessCI
  artifacts:
    name: "tests"
    reports:
      junit:
        - $CI_PROJECT_DIR/tests/junit-test-results.xml
