include:
  - remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

Test:
  image: quay.io/ebi-ait/ingest-base-images:node_14.15.5-alpine
  stage: test
  before_script:
    - yarn install --frozen-lockfile --no-progress
    - apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
  script:
    - yarn lint
    - yarn test --watch false --browsers=ChromeHeadlessCI
  artifacts:
    name: "tests"
    reports:
      junit:
        - $CI_PROJECT_DIR/tests/junit-test-results.xml

# Override the Build job for the UI project
Build:
  stage: build
  tags:
    - dind
  script:
    - echo $QUAY_PASSWORD | docker login quay.io -u $QUAY_USERNAME --password-stdin
    - docker build --pull --build-arg SNYK_TOKEN=$SNYK_TOKEN -t $IMAGE_NAME --no-cache .
    - docker push $IMAGE_NAME
  variables:
    SNYK_TOKEN: $SNYK_TOKEN
