dss: dss.dev.data.humancellatlas.org
schema: schema.dev.data.humancellatlas.org
ingest: api.ingest.dev.archive.data.humancellatlas.org
broker: ingest.dev.archive.data.humancellatlas.org

domainWhitelist: "api.ingest.dev.archive.data.humancellatlas.org,ingest.dev.archive.data.humancellatlas.org"
securedEndpoints: '\/auth\/.*,\/user\/.*,\/submissionEnvelopes$,\/projects$'
aaiClientId: "e2041c2d-9449-4468-856e-e84711cebd21"
aaiAuthority: "https://login.elixir-czech.org/oidc/"
olsUrl: "https://ontology.dev.archive.data.humancellatlas.org"
