dss: dss.staging.data.humancellatlas.org
schema: schema.staging.data.humancellatlas.org
ingest: api.ingest.staging.archive.data.humancellatlas.org
broker: ingest.staging.archive.data.humancellatlas.org

domainWhitelist: "api.ingest.staging.archive.data.humancellatlas.org,ingest.staging.archive.data.humancellatlas.org"
securedEndpoints: '\/auth\/.*,\/user\/.*,\/submissionEnvelopes$,\/projects$'
aaiClientId: "e2041c2d-9449-4468-856e-e84711cebd21"
aaiAuthority: "https://login.elixir-czech.org/oidc/"
olsUrl: "https://ontology.staging.archive.data.humancellatlas.org"
